# Generated by Django 4.2.11 on 2024-06-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_alter_task_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_posted",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
