# Generated by Django 4.2.11 on 2024-06-20 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0003_alter_task_date_posted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_posted",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
